CREATE TABLE smzdm
(
id INT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
article_id VARCHAR(20),
article_url VARCHAR(100),
title VARCHAR(50),
price VARCHAR(50),
source VARCHAR(50),
time TIMESTAMP,
submit_time TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
